### ISSUE TITLE
Cases fail when customising PFTs

### ISSUE THREAD

**Issue by evalieungh** [NorESMhub/noresm-land-sites-platform#121]
@lasseke and I both got errors with the `develop` branch now when we tried to run cases without some of the PFTs. Looks like the PFT index swapper is involved somehow. 

Log from Lasse:

```
Traceback (most recent call last):
noresm_landsites_platform-tasks-1     |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
noresm_landsites_platform-tasks-1     |     R = retval = fun(*args, **kwargs)
noresm_landsites_platform-tasks-1     |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
noresm_landsites_platform-tasks-1     |     return self.run(*args, **kwargs)
noresm_landsites_platform-tasks-1     |   File "/ctsm-api/app/tasks/cases.py", line 269, in run_case
noresm_landsites_platform-tasks-1     |     run_cmd(
noresm_landsites_platform-tasks-1     |   File "/ctsm-api/app/tasks/cases.py", line 63, in run_cmd
noresm_landsites_platform-tasks-1     |     raise Exception(proc.stderr.decode("utf-8").strip())
noresm_landsites_platform-tasks-1     | Exception: /ctsm-api/resources/ctsm/components/clm/src/fates/tools/FatesPFTIndexSwapper.py:147: DeprecationWarning: Please use `netcdf_file` from the `scipy.io` namespace, the `scipy.io.netcdf` namespace is deprecated.
noresm_landsites_platform-tasks-1     |   fp_out = netcdf.netcdf_file(output_fname, 'w')
noresm_landsites_platform-tasks-1     | /ctsm-api/resources/ctsm/components/clm/src/fates/tools/FatesPFTIndexSwapper.py:149: DeprecationWarning: Please use `netcdf_file` from the `scipy.io` namespace, the `scipy.io.netcdf` namespace is deprecated.
noresm_landsites_platform-tasks-1     |   fp_in  = netcdf.netcdf_file(input_fname, 'r')
noresm_landsites_platform-tasks-1     | Traceback (most recent call last):
noresm_landsites_platform-tasks-1     |   File "/ctsm-api/resources/ctsm/components/clm/src/fates/tools/FatesPFTIndexSwapper.py", line 274, in <module>
noresm_landsites_platform-tasks-1     |     main(sys.argv)
noresm_landsites_platform-tasks-1     |   File "/ctsm-api/resources/ctsm/components/clm/src/fates/tools/FatesPFTIndexSwapper.py", line 201, in main
noresm_landsites_platform-tasks-1     |     tmp_out[id] = fp_in.variables.get(key).data[ipft-1]
noresm_landsites_platform-tasks-1     | IndexError: index 6 is out of bounds for axis 0 with size 5
noresm_landsites_platform-tasks-1     | /usr/local/lib/python3.10/site-packages/scipy/io/_netcdf.py:304: RuntimeWarning: Cannot close a netcdf_file opened with mmap=True, when netcdf_variables or arrays referring to its data still exist. All data arrays obtained from such files refer directly to data on disk, and must be copied before the file can be cleanly closed. (See netcdf_file docstring for more information on mmap.)
```

**Comment by evalieungh** [comment]
Just tested this again and it's still a problem

```
api_1       | INFO:     172.18.0.1:52842 - "GET /api/v1/cases/a51a3adffa95140210c9eaaf4dc9aeaf HTTP/1.1" 200 OK
tasks_1     | [2022-09-06 12:10:13,879: INFO/ForkPoolWorker-8] Finished ./check_input_data in 83.15906023979187 seconds
tasks_1     | [2022-09-06 12:10:14,430: INFO/ForkPoolWorker-8] Running /ctsm-api/resources/ctsm/components/clm/src/fates/tools/FatesPFTIndexSwapper.py --pft-indices 1,2,6,7,8,9,10,11,12 --fin /ctsm-api/resources/data/a51a3adffa95140210c9eaaf4dc9aeaf_2/inputdata/lnd/clm2/paramdata/fates_params_api.22.1.0_12pft_c220307.nc --fout /tmp/tmpd020m4q0
tasks_1     | [2022-09-06 12:10:14,696: INFO/ForkPoolWorker-8] Finished /ctsm-api/resources/ctsm/components/clm/src/fates/tools/FatesPFTIndexSwapper.py in 0.26600217819213867 seconds
tasks_1     | [2022-09-06 12:10:14,708: INFO/ForkPoolWorker-8] Running /ctsm-api/resources/ctsm/components/clm/src/fates/tools/FatesPFTIndexSwapper.py --pft-indices 1,2,6,7,8,9,10,11,12 --fin /ctsm-api/resources/data/a51a3adffa95140210c9eaaf4dc9aeaf_2/inputdata/lnd/clm2/paramdata/fates_params_api.22.1.0_12pft_c220307.nc --fout /tmp/tmpfowakafl
tasks_1     | [2022-09-06 12:10:14,978: INFO/ForkPoolWorker-8] Finished /ctsm-api/resources/ctsm/components/clm/src/fates/tools/FatesPFTIndexSwapper.py in 0.2704324722290039 seconds
tasks_1     | [2022-09-06 12:10:14,994: ERROR/ForkPoolWorker-8] Task app.tasks.cases.run_case[9433aeeb-7ca5-4f3f-8785-b2e8dc090575] raised unexpected: Exception('/ctsm-api/resources/ctsm/components/clm/src/fates/tools/FatesPFTIndexSwapper.py:147: DeprecationWarning: Please use `netcdf_file` from the `scipy.io` namespace, the `scipy.io.netcdf` namespace is deprecated.\n  fp_out = netcdf.netcdf_file(output_fname, \'w\')\n/ctsm-api/resources/ctsm/components/clm/src/fates/tools/FatesPFTIndexSwapper.py:149: DeprecationWarning: Please use `netcdf_file` from the `scipy.io` namespace, the `scipy.io.netcdf` namespace is deprecated.\n  fp_in  = netcdf.netcdf_file(input_fname, \'r\')\nTraceback (most recent call last):\n  File "/ctsm-api/resources/ctsm/components/clm/src/fates/tools/FatesPFTIndexSwapper.py", line 274, in <module>\n    main(sys.argv)\n  File "/ctsm-api/resources/ctsm/components/clm/src/fates/tools/FatesPFTIndexSwapper.py", line 201, in main\n    tmp_out[id] = fp_in.variables.get(key).data[ipft-1]\nIndexError: index 9 is out of bounds for axis 0 with size 9\n/usr/local/lib/python3.10/site-packages/scipy/io/_netcdf.py:304: RuntimeWarning: Cannot close a netcdf_file opened with mmap=True, when netcdf_variables or arrays referring to its data still exist. All data arrays obtained from such files refer directly to data on disk, and must be copied before the file can be cleanly closed. (See netcdf_file docstring for more information on mmap.)\n  warnings.warn((')
tasks_1     | Traceback (most recent call last):
tasks_1     |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
tasks_1     |     R = retval = fun(*args, **kwargs)
tasks_1     |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
tasks_1     |     return self.run(*args, **kwargs)
tasks_1     |   File "/ctsm-api/app/tasks/cases.py", line 279, in run_case
tasks_1     |     run_cmd(
tasks_1     |   File "/ctsm-api/app/tasks/cases.py", line 63, in run_cmd
tasks_1     |     raise Exception(proc.stderr.decode("utf-8").strip())
tasks_1     | Exception: /ctsm-api/resources/ctsm/components/clm/src/fates/tools/FatesPFTIndexSwapper.py:147: DeprecationWarning: Please use `netcdf_file` from the `scipy.io` namespace, the `scipy.io.netcdf` namespace is deprecated.
tasks_1     |   fp_out = netcdf.netcdf_file(output_fname, 'w')
tasks_1     | /ctsm-api/resources/ctsm/components/clm/src/fates/tools/FatesPFTIndexSwapper.py:149: DeprecationWarning: Please use `netcdf_file` from the `scipy.io` namespace, the `scipy.io.netcdf` namespace is deprecated.
tasks_1     |   fp_in  = netcdf.netcdf_file(input_fname, 'r')
tasks_1     | Traceback (most recent call last):
tasks_1     |   File "/ctsm-api/resources/ctsm/components/clm/src/fates/tools/FatesPFTIndexSwapper.py", line 274, in <module>
tasks_1     |     main(sys.argv)
tasks_1     |   File "/ctsm-api/resources/ctsm/components/clm/src/fates/tools/FatesPFTIndexSwapper.py", line 201, in main
tasks_1     |     tmp_out[id] = fp_in.variables.get(key).data[ipft-1]
tasks_1     | IndexError: index 9 is out of bounds for axis 0 with size 9
tasks_1     | /usr/local/lib/python3.10/site-packages/scipy/io/_netcdf.py:304: RuntimeWarning: Cannot close a netcdf_file opened with mmap=True, when netcdf_variables or arrays referring to its data still exist. All data arrays obtained from such files refer directly to data on disk, and must be copied before the file can be cleanly closed. (See netcdf_file docstring for more information on mmap.)
tasks_1     |   warnings.warn((
```

**Comment by ka7eh** [comment]
Fixed in https://github.com/NorESMhub/ctsm-api/commit/589dc2828b3321d0c4f0f070400df96b70ccd0d2.
